FROM docker.io/python:3.8

# Test disabled network access
RUN if curl -IsS www.google.com; then echo "Has network access!"; exit 1; fi

# Print cachi2 env vars file
RUN cat /tmp/cachi2.env

# Check pip deps
RUN ls /tmp/pip_e2e_test-output/deps/pip

# Check content of source repository folder
RUN ls /tmp/pip_e2e_test-source/

WORKDIR /tmp/pip_e2e_test-source

# Install packages
RUN . /tmp/cachi2.env && python3 -m pip install -r requirements.txt
RUN cp /tmp/pip_e2e_test-source/src/test_package_cachi2/main.py /opt/test_package_cachi2
