FROM registry.fedoraproject.org/fedora:40

# Test disabled network access
RUN if curl -IsS www.google.com; then echo "Has network access!"; exit 1; fi

RUN cp -r /tmp/generic_e2e-output/deps/generic/ /deps

CMD ["ls", "-al", "/deps"]