# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "Dockerfile"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      # pydantic is designed to be used with a single version of pydantic-core [1] which follows a
      # different release cycle and is our nr.1 violator of version updates blocking other
      # dependency version updates to be accepted
      - dependency-name: "pydantic-core"
