import json

import pytest
from pyarn import lockfile  # type: ignore

from cachi2.core.package_managers.yarn_classic.project import ConfigFile, PackageJson, YarnLock
from cachi2.core.rooted_path import RootedPath

VALID_PACKAGE_JSON_FILE = """
{
  "name": "camelot",
  "packageManager": "yarn@3.6.1"
}
"""

EMPTY_JSON_FILE = "{}"

INVALID_JSON = "totally not json"

VALID_YARN_LOCK_FILE = """
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
package-1@^1.0.0:
  version "1.0.3"
  resolved "https://registry.npmjs.org/package-1/-/package-1-1.0.3.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
"""

EMPTY_YARN_LOCK_FILE = ""

# The version line (`yarn lockfile v1`) is required
INVALID_YARN_LOCK_FILE = """
package-1@^1.0.0:
  version "1.0.3"
  resolved "https://registry.npmjs.org/package-1/-/package-1-1.0.3.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
"""


def _prepare_config_file(
    rooted_tmp_path: RootedPath, config_file_class: ConfigFile, filename: str, data: str
) -> ConfigFile:
    path = rooted_tmp_path.join_within_root(filename)

    with open(path, "w") as f:
        f.write(data)

    return config_file_class.from_file(path)


@pytest.mark.parametrize(
    "config_file_class, config_file_name, config_file_content, content_kind",
    [
        pytest.param(
            PackageJson, "package.json", VALID_PACKAGE_JSON_FILE, "json", id="package_json"
        ),
        pytest.param(YarnLock, "yarn.lock", VALID_YARN_LOCK_FILE, "pyarn", id="yarnlock"),
    ],
)
def test_find_and_open_config_file(
    rooted_tmp_path: RootedPath,
    config_file_class: ConfigFile,
    config_file_name: str,
    config_file_content: str,
    content_kind: str,
) -> None:
    found_config = _prepare_config_file(
        rooted_tmp_path=rooted_tmp_path,
        config_file_class=config_file_class,
        filename=config_file_name,
        data=config_file_content,
    )

    if content_kind == "json":
        assert found_config.data == json.loads(config_file_content)
    elif content_kind == "pyarn":
        assert found_config.data == lockfile.Lockfile.from_str(config_file_content).data


# @pytest.mark.parametrize(
#     "is_pnp_install, nodeLinker",
#     [
#         pytest.param(True, "pnp", id="nodeLinker-pnp"),
#         pytest.param(True, "node-modules", id="nodeLinker-node-modules"),
#         pytest.param(False, "", id="regular-workflow"),
#     ],
# )
# def test_pnp_installs_detection(
#     rooted_tmp_path: RootedPath, is_pnp_install: bool, nodeLinker: str
# ) -> None:
#     _prepare_package_json_file(rooted_tmp_path, VALID_PACKAGE_JSON_FILE)
#     project = Project.from_source_dir(rooted_tmp_path)

#     if is_pnp_install:
#         _check_pnp_installs(nodeLinker, rooted_tmp_path)
#     assert project.is_pnp_install is is_pnp_install
