FROM docker.io/golang:1.22.0 AS build

# Test disabled network access
RUN if curl -IsS www.google.com; then echo "Has network access!"; exit 1; fi

# Print cachi2 env vars file
RUN cat /tmp/cachi2.env

# Check content of source repository folder
RUN ls /tmp/gomod_1.22_e2e_workspace_vendoring-source

WORKDIR /tmp/gomod_1.22_e2e_workspace_vendoring-source/hi/hiii
RUN . /tmp/cachi2.env && go build -o /usr/bin/hiii

CMD hiii
