FROM docker.io/python:3.11

# check network access
RUN if curl -IsS www.google.com; then echo "Has network access!"; exit 1; fi

# check source code
RUN cat /tmp/cachi2.env
RUN ls /tmp/pip_e2e_test_wheels-output/deps/pip
RUN ls /tmp/pip_e2e_test_wheels-source

WORKDIR /tmp/pip_e2e_test_wheels-source

# install packages
RUN . /tmp/cachi2.env && pip install -r requirements.txt
RUN cp /tmp/pip_e2e_test_wheels-source/package/main.py /opt/package

