apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cachi2-on-release
  annotations:
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[release]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/redhat-appstudio/cachi2:{{revision}}"
    - name: dockerfile
      value: Containerfile
  tasks:
    - name: say-hello
      taskSpec:
        steps:
          - image: ubuntu
            script: echo 'hello there'
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
