name: Mult-Arch-Build

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build Cachi2 image
    runs-on: ubuntu-latest
    steps:
      - name: add checkout action...
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build Cachi2 image
        uses: redhat-actions/buildah-build@v2
        with:
          image: cachi2
          tags: ${{ github.sha }}
          platforms: linux/amd64,linux/ppc64le
          containerfiles: |
            ./Containerfile
      - name: Check image created and Cachi2 version
        run: |
          buildah images | grep 'cachi2'
          podman run -t cachi2:${{ github.sha }} --version
     # Authenticate to container image registry to push the image
      - name: Podman Login
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PWD }}

      - name: Push image to Quay.io registry
        run: |
          podman manifest push cachi2:${{ github.sha }} \
            quay.io/containerbuildsystem/cachi2:${{ github.sha }}
          podman manifest push cachi2:${{ github.sha }} \
            quay.io/containerbuildsystem/cachi2:latest
